[settings]
update_rate = 1.0  # update rate in seconds

[curve]
fan-curve = [
    [10, 0],
    [20, 0],
    [30, 8],
    [40, 18],
    [50, 30],
    [55, 38],
    [60, 50],
    [65, 65],
    [70, 85],
    [80, 100],
    [90, 100]
]